// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvFxzooLjeaemXo5N6ytilBXaN2_SsUyI',
    appId: '1:664292153667:web:65d7415d9b0fd96b2ff7f6',
    messagingSenderId: '664292153667',
    projectId: 'weather-app-49f1b',
    authDomain: 'weather-app-49f1b.firebaseapp.com',
    storageBucket: 'weather-app-49f1b.firebasestorage.app',
    measurementId: 'G-RWHH83KWET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOSQHRlDoh5F7cf2_PFUFbKJwRssrFjAQ',
    appId: '1:664292153667:android:ea2abd57d79212182ff7f6',
    messagingSenderId: '664292153667',
    projectId: 'weather-app-49f1b',
    storageBucket: 'weather-app-49f1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2kM3aPt9_w5JFspWvoKbmA2IJ01d6ObA',
    appId: '1:664292153667:ios:9e31a735f567f1632ff7f6',
    messagingSenderId: '664292153667',
    projectId: 'weather-app-49f1b',
    storageBucket: 'weather-app-49f1b.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2kM3aPt9_w5JFspWvoKbmA2IJ01d6ObA',
    appId: '1:664292153667:ios:9e31a735f567f1632ff7f6',
    messagingSenderId: '664292153667',
    projectId: 'weather-app-49f1b',
    storageBucket: 'weather-app-49f1b.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvFxzooLjeaemXo5N6ytilBXaN2_SsUyI',
    appId: '1:664292153667:web:d1da98ed60148f442ff7f6',
    messagingSenderId: '664292153667',
    projectId: 'weather-app-49f1b',
    authDomain: 'weather-app-49f1b.firebaseapp.com',
    storageBucket: 'weather-app-49f1b.firebasestorage.app',
    measurementId: 'G-SJYKF6DRG6',
  );
}
